name: coverage-to-codecov

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  coverage:
    name: Run tests, collect coverage, upload to Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"
          scope: "@cloudwalk"

      - name: Copy .env file
        run: cp .env.example .env

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHA_PAT }}

      - name: Run tests with coverage
        run: npx hardhat coverage

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
