name: test-pr

on:
  workflow_call:
    secrets:
      GHA_PAT:
        required: true
jobs:
  build:
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node-version: [lts/*]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          registry-url: "https://npm.pkg.github.com"
          scope: "@cloudwalk"

      - name: Copy .env file
        run: cp .env.example .env

      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHA_PAT }}

      - run: npx hardhat compile

      - run: npm run test

      - run: npm run prettier:check

      - run: npm run eslint:check

# TODO: maybe split this into two workflows: one for PRs and one for main branch